#+TITLE: 感染症の確率シミュレーション
#+SUBTITLE: 数理モデルと相転移現象
#+AUTHOR: N. Murata 
#+SUBJECT: メモ
#+KEYWORD: 感染症，確率モデル，感染拡大，非線形力学，相転移，パーコレーション
#+LANGUAGE: japanese

#+LaTeX_CLASS: memo
#+LaTeX_CLASS_OPTIONS: [10pt,oneside]
#+STARTUP: overview
#+STARTUP: hidestars
#+OPTIONS: date:t H:4 num:t toc:nil \n:nil
#+OPTIONS: @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t 
#+OPTIONS: skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+LINK_UP:
#+LINK_HOME:

* はじめに

感染爆発(pandemic)を防ぐために，
外出の抑制など感染者との接触の機会を減らす努力が行われているが，
数理的な観点からこれがどのように影響するかを定性的に調べる．

以降の実験はR言語を用いて行っている．
実験に用いたRscriptは
[[https://github.com/noboru-murata/epidemic-model][GitHub]]
から参照できる．

* 数理モデル
# 具体的な問題を簡略化して本質を捉えるのが数理モデルの役割

人が相互に接触して感染症が拡大する過程は，
数理的にはグラフ上の確率的な拡散過程としてモデル化することができる．
# 人の集合，すなわち集団の関係を数理的に表すには一般にグラフが用いられる．
ウイルスの拡散に限らず，
噂の伝搬や情報の漏曳など
ある対象から別の対象へ繋がる経路を通って，
何かが伝わる現象のモデル化として一般化できる．
グラフとは頂点 (vertex, node) と辺 (edge, link) からなり，
複数の対象の関係を表現するための数学的な道具である．

まず，感染のモデルを記述するための用語を定義する．
- 頂点 :: グラフの構成要素で，本稿では人に対応する．
  以下では $i$ 番の人を表す場合に頂点 $i$ と書く．
- 辺 :: グラフのもう一つの構成要素で，頂点同士の繋がりを表す．
  頂点 $i$ と $j$ の間に辺があるとき，これを辺 $ij$ と書く．
  感染の可能性のある接触機会の有無を辺の有無で表し，
  実際に感染するかどうかは以下の感染確率で表現する．[fn:1]
- 感染確率 :: 感染者と未感染者が接触の機会を持ったときに感染が起こる確率を表す．[fn:2]
- 潜伏期間 :: 感染から発症までの期間を指す．この期間の接触は感染を引き起さないとする．
- 発症期間 :: 感染者から他者に感染することが可能な期間を指す．[fn:3]
  感染者は潜伏期間および発症期間中は自由に動けるものとし，
  以降は隔離されると考える．[fn:4]

さて，これらの概念を用いて簡便な感染過程を考える．

各頂点は，
未感染(susceptible)，
潜伏(latent)，
発症(present),
隔離(removed)の4状態を取るものとする．
未感染以外の状態(潜伏・発症・隔離)を
感染(infected)と呼ぶことにする．

感染した頂点は潜伏期間ののち発症し，
他者に感染可能となる発症期間に以降する．
発症した頂点と直接辺で結ばれている未感染の頂点は，
感染確率に従って感染し潜伏に遷移するか，
感染せずにそのまま未感染の状態を維持する．
発症した頂点は発症期間を経て隔離されるものとする．
現実の過程では，
- 感染確率 (他者に感染させる確率)
- 潜伏期間 (感染から発症に至る期間)
- 発症期間 (隔離されるまで感染を媒介する期間)
のいずれもが感染者ごとに異なると考えられるが，
ここでは簡単のため全ての感染者に対して同一であるとしてモデル化する．

記号を定義し，定式化すると以下のようになる．
時刻 $t$ における頂点 $i$ の状態を $S_{i}(t)$ で表し，
潜伏期間を $\Delta L$ ，
発症期間を $\Delta P$ で表すことにする．
頂点は非負の整数値を取り，
その値はそれぞれ以下の状態に対応する．
#+begin_export latex
\begin{align}
  S_{i}(t)\in\mathcal{N}_{S}
  &=\braces{0}&&\text{(未感染)}\\
  S_{i}(t)\in\mathcal{N}_{L}
  &=\braces{1,\dotsc,\Delta L}&&\text{(潜伏)}\\
  S_{i}(t)\in\mathcal{N}_{P}
  &=\braces{\Delta L{+}1,\dotsc,\Delta P}&&\text{(発症)}\\
  S_{i}(t)\in\mathcal{N}_{R}
  &=\braces{\Delta P{+}1,\dotsc}&&\text{(隔離)}
\end{align}
% \begin{equation}
%   S_{i}(t)
%   =
%   \begin{cases}
%     0,&\text{(未感染)}\\
%     [1,\Delta L] &\text{(潜伏)}\\ 
%     \Delta L +[1,\Delta P] &\text{(発症)}\\
%     -1 &\text{(隔離)}
%   \end{cases}
% \end{equation}
#+end_export
したがって，
状態$S_{i}(t)$ には
頂点 $i$ が感染してからの単位時間数が保持されることになる．

頂点 $i$ と $j$ の間に辺 $ij$ があり，
頂点 $i$ は未感染で，
頂点 $j$ が発症期間にある場合，
感染は確率 $p$ で各辺ごとに独立に起こるとする．
#+begin_export latex
\begin{align}
  \Prob{\text{頂点$j$から$i$に感染する}} &=p\\
  \Prob{\text{頂点$j$から$i$に感染しない}}&=1-p
\end{align}
#+end_export
まとめると状態の遷移は以下の規則に従って
単位時間ごとに行われる．
#+begin_export latex
\begin{equation}
  S_{i}(t{+}1)
  =
  \begin{cases}
    0,&\text{(未感染)}\\
    1,&\text{(新たな感染)}\\
    %-1,&\text{(隔離)}\;S_{i}(t)=-1\;\text{または}\;\Delta L + \Delta P\\
    S_{i}(t)+1&\text{(それ以外)}
  \end{cases}
\end{equation}
#+end_export
以上が，基本的なモデルとなる．

現実を模擬するには，
- どのようなグラフ構造(人と人の繋がり)を想定するのか?
- 離散時間モデルの単位時間(以下では日を想定する)に対して潜伏期間，発症期間をどのように設定するか?
- 感染確率をどの程度に見積るのか?
という点が肝要となる．

* 感染の推移

まず，比較的小さなグラフを用いて
感染モデルの数値実験を行い，
その結果を視覚化する．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \GraphFile{figs/exp1}
  \myGraph[.3]{張替確率$=0$(規則的なグラフ)}
  \myGraph[.3]{張替確率$=0.05$}
  \myGraph[.3]{張替確率$=1$(ランダムグラフ)}
  \sidecaption{Watts-Strogatzのモデル．
    張替確率を変えることによって規則的な構造から
    ランダムな構造を持つものまで多様なグラフを生成することができる．
    \label{fig:exp1-1}}
\end{figure*}
#+end_export

以下では集団のグラフ構造の生成モデルとして
Watts-Strogatzのモデルを用いる．[fn:5]
このモデルは
リング状に配置された頂点の近傍にのみ辺がある規則的なグラフを初期値とし，
適当な確率で辺の張り替えを行って生成されるグラフである．
辺の総数は変わらないが，
辺を張り替える確率を制御することで，
規則的なグラフからランダムなグラフまで
さまざまなグラフを生成することができる．[fn:6]
なお，直接結合する近傍の頂点の数，
すなわち頂点に結合する辺の数を次数と呼ぶ．
図\ref{fig:exp1-1}に示したのは，
頂点数30，
初期次数6，
張替確率を0,0.05,1とした場合に生成されるグラフの例である．

#+begin_export latex
\begin{figure}[htbp]
  \centering
  \myGraph{$t=1$}
  \setcounter{GraphPage}{8}\myGraph{$t=5$}
  \setcounter{GraphPage}{13}\myGraph{$t=10$}
  \setcounter{GraphPage}{18}\myGraph{$t=15$}
  \setcounter{GraphPage}{23}\myGraph{$t=20$}
  \setcounter{GraphPage}{28}\myGraph{$t=25$}
  \setcounter{GraphPage}{33}\myGraph{$t=30$}
  \myGraph{感染率の推移}
  \sidecaption[][-12\baselineskip]%
  {感染拡大の確率シミュレーション．
    (a)-(g)は感染状態の遷移を，
    (h)は感染率(感染した頂点の数/全頂点数)の推移を示す．
    頂点の色は状態に対応し
    \newline
    \begin{tabular}{l@{ : }l}
      白色 & 未感染\\
      黄色 & 潜伏\\
      赤色& 発症\\
      灰色& 隔離
    \end{tabular}
    \newline
    である．
    時間経過とともに辺を伝わって感染が拡大していく様子がわかる．
    この実験設定では30日でほぼ全員が感染した状態になる．
    % 頂点の色は状態に対応し，
    % 白色は未感染，黄色は潜伏，赤色は発症，灰色は隔離に対応する．
    % 時間経過とともに未感染者が減少していく様子がわかる．
    \label{fig:exp1-2}}
\end{figure}
#+end_export

次に，
表\ref{tab:exp1}に示すパラメタのもとで生成したグラフ上を
感染が拡大する様子を模擬した数値実験の結果を
図\ref{fig:exp1-2}に示す．
図\ref{fig:exp1-2}(a)は系全体の初期状態である．
頂点同士を結ぶ辺の数から
各頂点の接触機会は6程度であることが見てとれる．
頂点の状態は色で区別され，
白色は未感染，黄色は潜伏，赤色は発症，灰色は隔離に
対応している．
図\ref{fig:exp1-2}(a)から(g)までは，
時間(以下単位時間を1日と考える)の経過とともに
感染状態がどのように拡散し遷移していくかを示している．
実験設定では感染確率は0.5であるが，
発症期間を3日として実験しているので，
3日とも感染しない確率は $(1-0.5)^3=0.125$ である．
したがって接触している3日間で隣接するほぼ全ての頂点に感染が起こり，
30日で系全体に感染が拡大していく様子が見てとれる．
全頂点数に対する感染した頂点の数を感染率と定義し，
図\ref{fig:exp1-2}(h)にこの推移を示している．
感染者が少ない初期は拡がり方(感染率)はゆっくりとしているが，
拡がり始めると指数的に速度が上昇することがわかる．

#+begin_export latex
\begin{margintable}
  \caption{実験設定}
  \label{tab:exp1}
  % \centering
  \small
  \begin{tabular}{ll}
    \toprule
    パラメタ&値 \\
    \midrule
    頂点数&100 \\
    初期次数&6\;($3\times2$) \\
    張替確率&0.05 \\
    感染確率&0.5 \\
    潜伏期間&3 \\
    発症期間&3 \\
    \bottomrule
  \end{tabular}
\end{margintable}
#+end_export

* 確率的なばらつきの評価

確率的な数値実験では，
乱数系列の違いによって結果はばらつくことになる．
このため複数回の実験により可能性を網羅し，
実験で得られる知見の妥当性を担保する必要がある．[fn:7]

以下の実験では，
こうしたばらつきがどの程度あるかを確認する．
乱数によって生成している不確定な項目としては
- 発症者から未感染者への感染
- 感染の発生源
- 集団のグラフの構造
があるので，これらを順に検討する．
ここでも集団のグラフ構造の生成には
Watts-Strogatzのモデルを用いることとし，
実験の設定を表\ref{tab:exp2}にまとめる．

#+begin_export latex
\begin{margintable}
  \caption{実験設定}
  \label{tab:exp2}
  % \centering
  \small
  \begin{tabular}{ll}
    \toprule
    パラメタ&値 \\
    \midrule
    頂点数&10000 \\
    初期次数&50\;($25\times2$) \\
    張替確率&0.05 \\
    感染確率&0.04 \\
    潜伏期間&3 \\
    発症期間&3 \\
    \bottomrule
  \end{tabular}
\end{margintable}
#+end_export

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \GraphFile{figs/exp2}
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{感染の確率的な選択によるばらつき．
    感染拡大の始まる時期は異なるが，
    拡大の指数的な速度の性質はほとんど変わらないことがわかる．
    \label{fig:exp2-1}}
\end{figure*}
#+end_export

まず，
集団のグラフも初期の感染者も固定して，
各辺で感染が起こるかどうかのみランダムに選択したとき，
どの程度結果に違いがあるのか確認する．
感染の推移を図\ref{fig:exp2-1}に示す．
左図は集団全体に対する感染者の比率の推移を，
右図は感染者数の対数値(常用対数)の推移を示したものである．
感染の拡大期には患者数 $X(t)$ は指数的に増加する．
#+begin_export latex
\begin{equation}
  X(t)\simeq C\exp(\lambda t)
  % (=C 10^{\lambda' t})
\end{equation}
#+end_export
このとき
#+begin_export latex
\begin{equation}
  \frac{X(t+1)}{X(t)}
  =\exp(\lambda)
\end{equation}
#+end_export
であるから，
$\lambda$ は
単位時間あたりの感染者の増加率(感染速度)を表す量となる．
感染者数 $X(t)$ の両辺の対数を取ると
#+begin_export latex
\begin{equation}
  \log X(t) \simeq \lambda t + \log C
\end{equation}
#+end_export
となることから，
感染者数の対数を示した右図の傾きから
指数の係数 $\lambda$ を推定することができる．[fn:8]
さて，
図\ref{fig:exp2-1}の左図を見ると
初期の拡がり方にばらつきはあるものの，
右図から感染が拡大してからの速度はほぼ同じであることがわかる．
したがって，
感染が起こるかどうかの確率的な選択は
拡大開始の時期に影響を与えるが，
感染者が指数的に増大する時期の感染速度には
ほとんど影響しないことがわかる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{感染の発生源の違いによるばらつき．
    前の場合と同様に，
    感染拡大の始まる時期は異なるが，
    拡大の指数的な速度はほとんど変わらないことがわかる．
    \label{fig:exp2-2}}
\end{figure*}
#+end_export

次に感染の発生源の違いによるばらつきを確認する．
集団のグラフを固定して，
初期感染者をランダムに変えて実験した結果を
図\ref{fig:exp2-2}に示す．
図\ref{fig:exp2-1}と同様に
感染の拡大が開始される時間にばらつきはあるが，
拡大速度はほぼ同様であることが確認できる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{同じ特性とつグラフにおける感染の推移のばらつき．
    前の2つの実験と同様に，
    感染拡大の動的な性質はほとんど変わならいことがわかる．
    \label{fig:exp2-3}}
\end{figure*}
#+end_export

最後に，
初期次数と張替確率を固定してグラフを複数生成し，
それぞれのグラフ上の感染の推移を調べた結果を
図\ref{fig:exp2-3}に示す．
この実験でも同様に，
初期の拡がり方にばらつきはあるものの，
感染が拡大してからの速度はほぼ同じである．
したがって，集団のグラフ構造の特性が同じであれば，
感染の推移の性質は同様であることがわかる．

以上より，
確率的な数値実験により，
感染の拡大が始まる時期にばらつきがあるものの，
拡大の動的な性質は維持されていることがわかる．
以降のいくつかの項においては，
1つの実験結果を見ながら
拡大の速度の定性的な議論を行うこととする．

* グラフ構造の特性の影響

次に集団の関係をモデル化するグラフ構造の違いが，
感染の拡大にどのように影響を与えるか確認する．

グラフの生成モデルは様々なものが提案されているが，
これまで用いてきた
Watts-Strogatzのモデルに限定して，
その生成パラメタの変化が感染の拡がり方に及ぼす影響を調べることとする．

先にも述べたように
Watts-Strogatzのモデルは
規則的なグラフとランダムなグラフの中間的なグラフ構造を
生成することができるが，
ここで議論する特性パラメタとしては
- 初期グラフの次数(小さければ疎，大きければ密)
- 張替確率(小さければ規則的，大きければランダム)
を考える．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \GraphFile{figs/exp3}
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{初期次数の影響．
    近傍が最も少ないとき感染の拡大は途中で停止している．
    近傍が増加するに従って感染速度は上がるが，
    ある程度で速度はほぼ飽和する．
    \label{fig:exp3-1}}
\end{figure*}
#+end_export

まず，初期グラフの次数の影響を調べた結果を
図\ref{fig:exp3-1}に示す．
左右の図は，
前項と同様にそれぞれ感染率の推移と感染者数の対数の推移である．
ここで次数以外の実験設定は
表\ref{tab:exp2}の値を用いている．

次数が最も小さい10のときは，
感染は集団全体に拡がることなく一部の発症のみで終息している．
それ以外では感染はほぼ集団全体に蔓延しているが，
その中でも次数が少ない場合には拡大の速度は小さい．
辺の総数は次数 $\times$ 頂点数 $/2$ であるため，
感染の可能性が次数(辺で結合している頂点の数)に比例して増大して
感染速度が増加すると考えられる．

一方，ある程度以上の次数になると
速度にそれほど大きな違いはないことがわかる．
感染に寄与する辺は一方が感染，もう一方が未感染であるが，
ある程度の数以上の辺があれば様々な経路で感染が拡がり，
十分な速度で近傍がほぼ全て感染者となるので，
# ある程度の近傍(辺で隣接した頂点)があれば十分な速度で感染が拡がり，
# 辺の両端が短時間で感染者になり，
結果として余分な辺は感染の伝播に寄与しなくなると考えられる．

次に，
張替確率を0から1まで変えて，
その影響を調べた結果を
図\ref{fig:exp3-2}に示す．
張替確率が0の場合は次数が一定のリング状の規則的なグラフであり，
1の場合は平均次数が初期値グラフと同じランダムなグラフとなる．
このモデルで生成されたグラフは
張替確率を変えても辺の総数は変わらず，
また各頂点から出る辺の数も平均的に変わらないが，
大きな張替確率で
ランダムになるほどリングの反対側に直接繋がる辺が存在する確率が高くなる．
ある頂点からリングの反対側の頂点への経路は，
規則的なグラフにおいては
辺の存在する隣接した頂点を順に辿って到達しなくてはいけないが，
ランダムなグラフでは
直接リングの反対側付近にある頂点に移動できる可能性が高いので，
経由しなくてはならない頂点の数は減少することになる．
# より一般的に言えば，
# ランダムネスが大きくなるほど，
# ある頂点から任意の頂点に到達するために経由する
# 平均的な頂点数は少なくなると考えられる．

1次元に配置した頂点間のユークリッド距離を空間上の距離と呼ぶことにする．
一方，グラフ上の距離を
ある頂点から他の頂点に移動するために必要な最小の辺の数と定義する．
2つの頂点が直接辺で繋がっていれば距離1，
別の頂点1つを経由して移動できる場合は距離2となる．
規則的な場合は空間上の距離とグラフ上の距離はほぼ同じであるが，
ランダムになると空間上の距離に比べてグラフ上の距離は平均的には著しく短くなる．[fn:9]
グラフ上の距離は感染が伝達する時間に比例し，
短ければ短時間で感染し，長ければ感染には時間が掛かる．
このことから，
グラフ全体に感染が拡がる時間は，
頂点間のグラフ上の平均距離に比例することが予想される．[fn:10]

さて，
張替確率が0の規則的なグラフの場合は，
感染の伝播が一定数で増加する特殊な伝播となっている．
上で考察したように，
規則的なグラフでは
最も遠い反対側の頂点に感染が伝わるまで順番に伝染していくため
と考えられる．

一方，
張替確率が0以外では，
一旦拡大しはじめると指数的に感染率が増加して蔓延している．
また張替確率がある程度大きければ，
ほぼ同じ速度で感染が拡大していることが見てとれる．
ランダムネスがちょっとあるだけで
感染の推移の性質ががらりと変わるのは，
上で考察したように，
任意の2頂点間の平均的な距離が短くなるため，
感染速度が拡大すると考えられる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{張替確率の影響．
    確率が大きくなるにしたがって感染速度は増大するが，
    この設定では0.03を越えると速度に大きな差がなくなっている．
    \label{fig:exp3-2}}
\end{figure*}
#+end_export

以上より，
感染の拡大においては
- 頂点の平均的な次数が大きい (接触する人数が多い)
- グラフのランダムネスが高い (空間的に離れた人と接触する)
ことが悪影響を与えていることがわかる．
実際の環境で人は移動しつつ他者と接触を持っているため，
移動経路上でさまざまな人と接触し，
また人により接触する人が異なるため，
集団のグラフは上記の悪影響の条件を備えていると考えられる．
逆に感染の拡大を防ぐためには，
次数が少なく規則的なグラフ構造にする必要があるが，
これは
感染しているか否かに関わらず，
移動が少なく，
空間上の距離の意味で近隣の少数の人としか接触しない状態を
維持しなくてはならないことになる．[fn:11]

* 感染モデルの特性の影響

次に感染モデルの特性が感染に与える影響を確認する．
実験設定において影響を調べるために変更した特性以外のパラメタは
表\ref{tab:exp2}の値を用いた．

# 単位時間を1日として話をしよう．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \GraphFile{figs/exp4}
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{潜伏期間の影響．
    潜伏期間が長くなると，
    感染速度が単調に減少していることがわかる．
    \label{fig:exp4-1}}
\end{figure*}
#+end_export

まず潜伏期間の影響を調べた結果を
図\ref{fig:exp4-1}に示す．
感染率の推移だけ見ると
拡大が始まる時期がずれているようにも見えるが，
対数表示すると明瞭に指数増大の傾きが単調に減少している．
潜伏期間の長さは同じ範囲に感染が拡大するのに掛かる時間に比例することになるので，
潜伏期間の長さは速度にきわめて単純な形で影響を与えることがわかる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{発症期間の影響．
    感染を媒介する発症期間が長くなれば
    感染速度は速くなり，
    ある程度の長さになると速度は飽和する．
    \label{fig:exp4-2}}
\end{figure*}
#+end_export

次に感染を媒介する発症期間の影響を調べた結果を
図\ref{fig:exp4-2}に示す．
発症期間が長ければ接触機会も増え，
実質的な感染の確率が増大することが予想される．
しかしながら，
感染速度は単純に増え続けるわけではない．
この実験設定では，
発症期間(隔離されるまでの間)が
1日の場合は感染速度は遅いが(傾きは小さい)，
それ以外は速度にそれほど差はない．[fn:12]

発症期間に
辺で直接繋がれた隣の人に感染しない確率は
#+begin_export latex
\begin{equation}
  \Prob{\text{隣りに感染しない}}
  =(1-\text{(感染確率)})^\text{(発症期間)}
\end{equation}
#+end_export
であるが，
この確率は
発症期間が長くなるに従って急速に0に近づくため，
隣の人が感染する確率
#+begin_export latex
\begin{equation}
  \Prob{\text{隣りが感染する}}
  =1-(1-\text{(感染確率)})^\text{(発症期間)}
\end{equation}
#+end_export
は急速に1に近づき飽和する．
つまり
ある程度発症期間が長ければ，
その長さによらず
ほぼ確実に感染が起こることになる．

また，
感染者が隔離されるまでに1名を越える人に感染させれば，
指数的(鼠算的)に感染者は増大するため，
したがって感染者が平均何名に媒介するかが重要となる．
まず，
近傍の誰にも感染しない確率は
#+begin_export latex
\begin{equation}
  \Prob{\text{近傍の誰にも感染しない}}
  =(1-\text{(感染確率)})^\text{(発症期間)$\times$(次数)}
\end{equation}
#+end_export
であり，
次数が大きい場合は発症期間の長さが短かくても
この値は小さな値となることがわかる．
近傍の1名以上が感染する確率は
#+begin_export latex
\begin{equation}
  \begin{multlined}
    \Prob{\text{近傍の1名以上が感染する}}\\
    =1-(1-\text{(感染確率)})^\text{(発症期間)$\times$(次数)}
  \end{multlined}
\end{equation}
#+end_export
であり，
近傍の1名のみが感染する確率は
#+begin_export latex
\begin{equation}
  \begin{multlined}
    \Prob{\text{近傍の1名のみが感染する}}\\
    =\text{(次数)}\times
    (1-\text{(感染確率)})^\text{(発症期間)$\times$(次数$-1$)}\\
    \times(1-(1-\text{(感染確率)})^\text{(発症期間)})
    % \sum_{t=1}^{\text{(発症期間)}}(1-\text{(感染確率)})^{t-1}\text{(感染確率)}
  \end{multlined}
\end{equation}
#+end_export
であるから，この差が2名以上感染する確率となる．
ある程度の次数と発症期間があれば1名のみが感染する確率は小さく，
ほぼ確実に2名以上に感染することになるため，
感染速度は容易に指数的になることがわかる．
このことから，
感染を拡大しないためには，
感染を媒介する期間を短くするために，
発症をすみやかに検知し，
できるだけ早く隔離することが重要であることがわかる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染率の推移}
  \myGraph{感染者数(常用対数)の推移}
  \sidecaption{感染確率の影響．
    感染確率が高くなるに従い
    感染速度は速くなるが，
    ある程度の確率で飽和する．
    一方，確率が低い場合に
    蔓延せずに感染が終息する場合がある．
    \label{fig:exp4-3}}
\end{figure*}
#+end_export

感染確率を変えると
少し異なる状況があらわれる．
これを調べた結果を図\ref{fig:exp4-3}に示す．
直感的に明らかなように，
感染確率が高くなるに従い感染速度は速くなり，
ある程度確率が高くなると，
発症期間を長くしたのと同様に
感染速度は飽和している．
一方，感染確率が低い場合に
ある確率を境として
蔓延せずに感染が終息している場合がある．
# 蔓延するかしないかが不連続に変化しているように見える

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染率の推移}
  \myGraph{感染確率と感染者数}
  \sidecaption{感染確率の影響による相転移．
    ある確率を境に感染が蔓延するかしないかの
    最終状態が異なっている．
    \label{fig:exp4-4}}
\end{figure*}
#+end_export

感染状況のこの不連続な変化を確認するために，
感染確率を低い範囲で動かしてより詳細に調べたのが
図\ref{fig:exp4-4}である．
この実験設定では0.01を境に，
ほとんど蔓延せずに終息するか，
感染が蔓延するかに分岐していることがわかる．
これは
パーコレーション(浸透; percolation)による
相転移現象の一種と考えられる．
次項では，この現象の仕組みを調べてみることにする．

* 感染拡大の相転移

前項では
感染確率を動かしながら，
感染拡大の劇的な変化(一種の相転移現象)を見たが，
これは感染確率とグラフ構造の相対的な関係で現れる．
感染確率を固定して，
グラフ構造を変えながら観測することもできるが，
ここでは
感染が蔓延するかどうかにだけ興味があるので，
感染の拡大を制御するパラメタについては
できるだけ簡便なものを考える．
見通しを良くするために規則的なグラフを考え，
感染確率のみを動かしながら，
その影響を探る．

2次元の格子状に並んだ頂点の集合を考え，
各頂点がその4近傍と辺で結ばれた規則的なグラフを考える．
それ以外の実験設定を表\ref{tab:exp5}にまとめる．

#+begin_export latex
\begin{margintable}
  \caption{実験設定}
  \label{tab:exp5}
  % \centering
  \small
  \begin{tabular}{ll}
    \toprule
    パラメタ&値 \\
    \midrule
    頂点数&4000 \\
    近傍数&4 \\
    感染確率&0.6 \\
    潜伏期間&0 \\
    発症期間&1 \\
    \bottomrule
  \end{tabular}
\end{margintable}
#+end_export

#+begin_export latex
\begin{figure}[htbp]
  \centering
  \GraphFile{figs/exp5}
  \myGraph{$t=1$}
  \setcounter{GraphPage}{15}\myGraph{$t=15$}
  \setcounter{GraphPage}{30}\myGraph{$t=30$}
  \setcounter{GraphPage}{45}\myGraph{$t=45$}
  \setcounter{GraphPage}{60}\myGraph{$t=60$}
  \myGraph{感染率の推移}
  \sidecaption[][-5\baselineskip]%格子グラフ上の感染の推移．
  {4近傍に辺のある2次元の格子上を感染が拡大していく様子．
    感染の増大は指数関数ほど速くはない．
    \label{fig:exp5-1}}
\end{figure}
#+end_export

図\ref{fig:exp5-1}に感染の推移を示す．
規則的ではあるが，
先の実験と同様に感染が拡大していく様子がわかる．
ただし，
感染率の推移を見るように，
感染者の増大は指数関数的ではなく，
ほぼ線形に増加している．

感染確率を変えて，
複数回実験した結果を
図\ref{fig:exp5-2}に示す．
各感染確率ごとに
時刻60での感染率を箱ひげ図で表示している．

#+begin_export latex
\begin{figure}[htbp]
  \sidecaption{感染確率と感染率の関係．
    感染確率の違いにより，
    十分時間が経過したあとの感染率が
    大きく変わることがわかる．
    \label{fig:exp5-2}}
  \centering
  \myGraph*{}
\end{figure}
#+end_export

十分時間が経過したあとの終息結果は，
感染確率の違いにより急激に変わる．
いくつかの感染確率について終息状態を示したのが，
図\ref{fig:exp5-3}である．
図\ref{fig:exp5-2}で見たように，
確率0.5の前後で状態が変わる．
低い確率では局所的な感染で終息しているが，
高い確率では大域的な蔓延となっている．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph[.3]{感染確率$=0.2$}
  \myGraph[.3]{感染確率$=0.5$}
  \myGraph[.3]{感染確率$=0.7$}
  \sidecaption{感染確率による終息状態の違い．
    低い感染確率では感染は局所的なものに留まっているが，
    高い確率では全体に蔓延している．
    \label{fig:exp5-3}}
\end{figure*}
#+end_export

感染確率が蔓延の仕方に及ぼす影響は，
以下のように近似的に解析できる．
無限遠点まで感染が拡がるか否かの確率
#+begin_export latex
\begin{equation}
  Q
  =\Prob{\text{頂点$i$から無限遠点まで感染しない}}
  \quad\text{(頂点$i$によらない)}
\end{equation}
#+end_export
を考える．
4つの頂点が隣接しているグラフを考えているので，
隣を経由して無限遠点まで感染が拡がるか否かは
感染確率を $P$ として以下のように考えられる．
#+begin_export latex
\begin{align}
  Q
  &=\Prob{\text{頂点$i$から無限遠点に到達する経路がない}}\\
  &=\Prob{\text{頂点$i$の4近傍を経由して無限遠点に到達する経路がない}}\\
  &\simeq\Prob{\text{頂点$i$の近傍$j$を経由して無限遠点に到達する経路がない}}^{4}\\
  &=\bigl(\Prob{\text{頂点$i$から近傍に経路がない}}\bigr.\\
  &\quad + \bigl.\Prob{\text{頂点$j$には行けるがそこから経路がない}}\bigr)^{4}\\
  &=\bigl\{
    \underbrace{(1-P)}_{i\not\to j}
    +
    \underbrace{P_{\phantom{j}}}_{i\to j}
    \times\underbrace{Q}_{j\not\to\infty}
    \bigr\}^{4}
\end{align}
#+end_export
4近傍の各点から無限遠への経路の有無は本来は独立ではないので
式はあくまで近似であるが，
定性的な議論としてはこれを認めてもらうこととし，
感染確率 $P$ に対して
以下の式を満たす $Q$ がどのような値となるかを考える．[fn:14]
#+begin_export latex
\begin{equation}
  Q=\{(1-P) + P\times Q \}^{4},\;(0\le Q\le 1)
\end{equation}
#+end_export
式の左辺と右辺をそれぞれ $R$ とし，
横軸を $Q$
縦軸を $R$ として
2つの関数
#+begin_export latex
\begin{align}
  R&=Q && \text{(緑線)}\\
  R&=\{(1-P) + P\times Q\}^{4} &&\text{(オレンジ・赤線)}
\end{align}
#+end_export
を重ね描きしたものが
図\ref{fig:exp6-1}(a)である．

#+begin_export latex
\begin{figure*}%[htbp]
  \sidecaption{格子グラフ上の感染の終息状態の定性的な解析．
    \label{fig:exp6-1}}
  \centering
  \GraphFile{figs/exp6}
  \myGraph{確率$Q$の満たす条件}
  \myGraph{感染確率と全感染率の関係}
\end{figure*}
#+end_export

# #+begin_export latex
# \begin{figure}%[htbp]
#   \sidecaption{確率$Q$の満たす条件．
#     \label{fig:exp6-1}}
#   \centering
#   \GraphFile{figs/exp6}
#   \myGraph*{}
# \end{figure}
#+end_export

$R=Q$ (緑線)と
$R=(Q\text{の4次式})$ (オレンジ・赤線)
の交点のうちで，
区間 $0\le Q\le 1$ に含まれるものが
条件を満たす $Q$ の値となる．
感染確率 $P$ の大小によって
解が $0\le Q\le 1$ の間を移動していく様子がわかる．

確率 $Q$ は感染が拡がらない確率なので，
終息期の全感染率は $1-Q$ で表される．
感染確率 $P$ と 
全感染率 $1-Q$ の関係を示すと
図\ref{fig:exp6-1}(b)となる．
これから閾値(この場合は $p=0.25$)を越えると
急速に全感染率が1に近付いくていことがわかる．[fn:13]

# #+begin_export latex
# \begin{figure}%[htbp]
#   \sidecaption{感染確率と全感染率の関係．
#     \label{fig:exp6-2}}
#   \centering
#   \myGraph*{}
# \end{figure}
#+end_export

* おわりに

感染そのものは医学的な問題であるが，
感染の拡大する仕組みは数理的な問題として定式化される．
本稿では，簡便ではあるが，
ある程度現実的な状況を模擬するモデルを構成し，
モデルの中のパラメタ
- 感染確率
- 発症期間
- 潜伏期間
の影響について議論した．
また時間が十分経ったとき，
系の状態としては
- 孤立した領域のみでの発症
- 全体に蔓延して終息
の2つがあるが，
感染確率の影響でこれらが分岐する機構についても調べた．

感染が拡大する場合には，その拡がり方は一般に指数的となるが，
- 治療方法の確立
- 治療体制の確保
- 治療薬・予防薬・ワクチンの開発
のためには，指数の増大を決める時定数を小さくすることが必須である．
感染確率を減らし，
グラフ構造を疎でランダムネスが低いものにすることによって，
場合によっては蔓延を避けることができるし，
最悪でも拡大の速度を減少させることができる．
人間が介入して変えられるのは，
感染確率と集団のグラフの構造である．
感染確率は接触機会と感染力の積であり，
感染力はウイルス固有のものなので，
感染確率を減らすには接触機会を減らすしかない．
またグラフ構造を変えるには，
長距離の移動や外出を避けるしかない．
ということで，結局人間ができることは限られている．

* Footnotes

[fn:14]この近似はかなり雑なので，
厳密な解析を知りたい場合は例えば
[[https://doi.org/10.1007/978-3-662-03981-6_11][Grimmett G. (1999) Bond Percolation in Two Dimensions. In: Percolation. Grundlehren der mathematischen Wissenschaften (A Series of Comprehensive Studies in Mathematics), vol 321. Springer, Berlin, Heidelberg]]
などを参照． 

[fn:13]厳密な解析による閾値は $p=0.5$ である．

[fn:1]ここで考える接触はいわゆる濃厚接触に限らず，
比較的密集した空間に同時に留まることがあり，
感染を引き起こす可能性のあるものを含めて考えることとする．
例えば，
会社の同じ部署にいる，
あるいは同じエレベータや電車などを使うなどを想定すれば良い．

[fn:2]接触機会に対して必ずしも感染が起こるとは限らないので，
この不確定性を確率的なものとして取り扱う．
接触機会として濃厚接触のみを考える場合は，
感染確率を1に近づければよい．

[fn:3]医学的な用語とは齟齬があるが，
モデルを簡潔に記述するために
発症してはじめて他者に感染させる可能性がある
ものとして扱う．

[fn:4]隔離には現実的には回復・死亡によるものも含まれる．

[fn:5]Watts, D., Strogatz, S. Collective dynamics of ‘small-world’ networks. Nature 393, 440–442 (1998). https://doi.org/10.1038/30918

[fn:6]たとえば [[https://jp.mathworks.com/help/matlab/math/build-watts-strogatz-small-world-graph-model.html][ワッツ・ストロガッツのスモール ワールド グラフのモデル作成 @ MathWorks]] 
などを参照．

[fn:7]多数回の実験は時間や計算資源といったコストが掛かるため，
知りたいことが単一または少数の実験でわかるなら，
少ない実験で済ませたい場合もある．
このため，
単一の実験でわかることとわからないことを見極める必要がある．

[fn:8]図では人数に換算しやすいように常用対数を用いたが，
対数の底は適宜取り直せばよい．

[fn:9]この考え方は探索の高速化のためにデータベースなどでも利用されている．

[fn:10]視点を変えて考えることもできる．
あるグラフの頂点同士の距離が与えられると，
その距離を実現するように
適当な次元(多くとも頂点数-1)の空間に
頂点を配置する(座標を与える)ことができる(多次元尺度構成法)．
規則的なグラフはもともとの配置に従って低次元空間の座標が与えられ，
ランダムなグラフの距離を実現するためには高次元空間の座標を与える必要がある．
ある1点から感染が拡大していく状況は
球面波が拡がっていく様子として捉えることができ，
感染者数は経過時間を半径とする球面内に含まれている体積に比例する．
したがって感染者の増大の仕方は
頂点が配置される空間の次元に依存し，
高次元空間ほど増大の仕方が急峻となる．

[fn:11]これは多くの国・自治体が要請している状態に他ならない．

[fn:12]実質上は潜伏期間と発症期間の比率が重要であり，
この比が感染の速度を決定していると考えられる．
潜伏期間の長さを単位時間と考えれば，
両方のパラメタをいじる必要はないが，
数値実験上は実際のパラメタと紐付け，
潜伏期間，発症期間をそれぞれ日を単位として扱いたいので，
単位時間を1日として考えている．
