#+TITLE: 感染症の確率シミュレーション
#+SUBTITLE: 数理モデルと相転移現象
#+AUTHOR: N. Murata 
#+SUBJECT: メモ
#+KEYWORD: 感染症，確率モデル，感染拡大，非線形力学，相転移，パーコレーション
#+LANGUAGE: japanese

#+LaTeX_CLASS: memo
#+LaTeX_CLASS_OPTIONS: [10pt,oneside]
#+STARTUP: overview
#+STARTUP: hidestars
#+OPTIONS: date:t H:4 num:t toc:nil \n:nil
#+OPTIONS: @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t 
#+OPTIONS: skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+LINK_UP:
#+LINK_HOME:

* はじめに

感染爆発(pandemic)を防ぐために，
外出の抑制など感染者との接触の機会を減らす努力が行われているが，
数理的な観点からこれがどのように影響するかを定性的に調べる．

具体的な問題を簡略化して本質を捉える．
数理モデルの役割

* 数理モデル

ウイルスの拡散，噂の伝搬，情報の漏曳など
ある点から別の点への経路を通って，
何かが伝わる現象のモデル化

人の集合，すなわち集団の関係を数理的に表すには，
一般にグラフが用いられる．
グラフは頂点 (vertex, node) と辺 (link, edge) からなる．
複数の対象の関連性を表現するための数学的な道具

人が接触して感染症が拡大している過程は，
数理的にはグラフ上の確率的な拡散過程としてモデル化することが一般的である．
まず，これらを記述するための用語を定義する．
- 頂点 :: グラフの構成要素で，本稿では人に対応する．
- 辺 :: グラフのもう一つの構成要素で，頂点同士の繋がりを表す．
  感染の可能性のある接触機会の有無を辺の有無で表し，
  実際に感染するかどうかは以下の感染確率で表現する．[fn:1]
- 感染確率 :: 感染者と未感染者が接触の機会を持ったときに感染が起こる確率を表す．[fn:2]
- 潜伏期間 :: 感染から発症までの期間を指す．この期間の接触は感染を引き起さないとする．
- 媒介期間 :: 感染者から他者に感染することが可能な期間を指す．[fn:3]
  感染者は感染してから媒介期間の間は自由に動けるものとし，
  以降は隔離されてると考える．

以下では，
これらの概念を用いて非常に簡便な感染過程を考える．

各頂点は，
未感染(susceptible)，
潜伏(latent)，
媒介(present),
隔離(removed)の4状態を取るものとする．
未感染以外の状態(潜伏・媒介・隔離)を
感染(infected)と呼ぶことにする．

感染した頂点は潜伏期間ののち発症し，
他者に感染可能となる媒介期間に以降する．
媒介可能な頂点(発症した頂点)と直接辺で結ばれている未感染の頂点は，
感染確率に従って感染し潜伏に遷移するか，
感染せずにそのまま未感染の状態を維持する．
発症した頂点は媒介期間を経て隔離されるものとする．

記号を定義し，定式化すると以下のようになる．

時刻 $t$ における頂点 $i$ の状態を $S_{i}(t)$ で表し，
潜伏期間を $\Delta L$ ，
媒介期間を $\Delta P$ で表すことにする．
頂点は非負の整数値を取り，
その値はそれぞれ以下の状態に対応する．
#+begin_export latex
\begin{align}
  S_{i}(t)\in\mathcal{N}_{S}
  &=\braces{0}&&\text{(未感染)}\\
  S_{i}(t)\in\mathcal{N}_{L}
  &=\braces{1,\dotsc,\Delta L}&&\text{(潜伏)}\\
  S_{i}(t)\in\mathcal{N}_{P}
  &=\braces{\Delta L+1,\dotsc,\Delta P}&&\text{(媒介)}\\
  S_{i}(t)\in\mathcal{N}_{R}
  &=\braces{\Delta P+1,\dotsc}&&\text{(隔離)}
\end{align}
% \begin{equation}
%   S_{i}(t)
%   =
%   \begin{cases}
%     0,&\text{(未感染)}\\
%     [1,\Delta L] &\text{(潜伏)}\\ 
%     \Delta L +[1,\Delta P] &\text{(発症)}\\
%     -1 &\text{(隔離)}
%   \end{cases}
% \end{equation}
#+end_export
状態$S_{i}(t)$ には
頂点 $i$ が感染してからの単位時間数が保持されることになる．

頂点 $i$ と $j$ の間に辺があり，
頂点 $i$ が未感染で，
頂点 $j$ が発症している(媒介期間にある)場合，
感染は以下のように
感染確率 $p$ で独立に起こるとする．
#+begin_export latex
\begin{align}
  \Prob{\text{$j$から$i$に新たに感染する}} &=p\\
  \Prob{\text{$j$から$i$に感染しない}}&=1-p
\end{align}
#+end_export
状態の遷移は以下の規則に従って行われるものとする．
#+begin_export latex
\begin{equation}
  S_{i}(t+1)
  =
  \begin{cases}
 
    1,&\text{(新たな感染が起こる)}\\
    %-1,&\text{(隔離)}\;S_{i}(t)=-1\;\text{または}\;\Delta L + \Delta P\\
    S_{i}(t)+1&\text{(それ以外)}
  \end{cases}
\end{equation}
#+end_export
以上が，基本的なモデルとなる．

現実を模擬するには，
- どのようなグラフ構造(人と人の関係を表す集団のネットワーク)を想定するのか?
- 上記の離散時間モデルの単位時間(以下では日を想定している)に対して潜伏期間，媒介期間をどのように設定するか?
- 感染確率をどの程度に見積るのか?
といった点が肝要となる．

* 感染の推移

まず，比較的小さなグラフを用いて
感染拡大の数値実験を行い，
その結果を視覚化する．

以下で用いる集団のネットワークは
Watts-Strogatzのモデルである．
リング状に配置された頂点の近傍にのみ辺があるグラフを初期値とし，
適当な確率で辺の張り替えを行って生成されるグラフである．
辺の総数は変わらないが，
張替確率を制御することで，
図\ref{fig:exp1-1}に示すような
規則的なグラフからランダムなグラフまで
さまざまなグラフを生成することができる．

#+begin_export latex
\begin{figure}[htbp]
  \sidecaption{Watts-Strogatzのモデル．
    張替確率を変えることによって規則的からランダムに
    構造が変化することがわかる．
    \label{fig:exp1-1}}
  \centering
  \GraphFile{figs/exp1}
  \myGraph{張替確率$=0$(規則的なグラフ)}
  \myGraph{張替確率$=0.05$}
  \myGraph{張替確率$=1$(ランダムグラフ)}
\end{figure}
#+end_export

#+begin_export latex
\begin{margintable}
  \caption{実験設定}
  \label{tab:exp1}
  % \centering
  \small
  \begin{tabular}{ll}
    \toprule
    パラメタ&値 \\
    \midrule
    頂点数&100 \\
    初期近傍&6\;($3\times2$) \\
    張替確率&0.05 \\
    感染確率&0.5 \\
    潜伏期間&3 \\
    媒介期間&3 \\
    \bottomrule
  \end{tabular}
\end{margintable}
#+end_export

#+begin_export latex
\begin{figure}[htbp]
  \sidecaption{感染拡大の確率シミュレーション．
    (a)-(g)は感染状態の遷移を表し，
    (h)は感染率(未感染でない頂点の数/全頂点数)の推移を示す．
    頂点の色は状態に対応し
    \newline
    \begin{tabular}{l@{ : }l}
      白色 & 未感染\\
      黄色 & 潜伏\\
      赤色& 媒介\\
      灰色& 隔離
    \end{tabular}
    \newline
    である．
    時間経過とともに辺を伝わて感染が拡大していく様子がわかる．
    % 頂点の色は状態に対応し，
    % 白色は未感染，黄色は潜伏，赤色は発症，灰色は隔離に対応する．
    % 時間経過とともに未感染者が減少していく様子がわかる．
    \label{fig:exp1-2}}
  \centering
  \myGraph{$t=1$}
  \setcounter{GraphPage}{8}\myGraph{$t=5$}
  \setcounter{GraphPage}{13}\myGraph{$t=10$}
  \setcounter{GraphPage}{18}\myGraph{$t=15$}
  \setcounter{GraphPage}{23}\myGraph{$t=20$}
  \setcounter{GraphPage}{28}\myGraph{$t=25$}
  \setcounter{GraphPage}{33}\myGraph{$t=30$}
  \myGraph{感染の推移}
\end{figure}
#+end_export

表\ref{tab:exp1}に示すパラメタを用いて
感染の拡大する様子を模擬した数値実験の結果を
図\ref{fig:exp1-2}に示す．
図(a)は系全体の初期状態である．
頂点同士を結ぶ辺の数から
各頂点の接触機会は6程度であることがわかる．
白色は未感染，黄色は潜伏，赤色は発症，灰色は隔離に
対応させ頂点の状態を表している．
図(g)までは，
時間の経過とともに感染状態がどのように遷移していくかを示している．
実験設定では感染確率は0.5であるが，
発症している3時刻の間に接触しているほぼ全ての頂点に感染が起こり，
系全体に感染が拡大していく様子が見てとれる．
全頂点数に対する未感染でない頂点の数を感染率と定義し，
図(h)にこの推移を示している．
感染者が少ない初期は拡がり方はゆっくりとしているが，
拡がり始めると指数的に速度が上昇することがわかる．

* 確率的な不確定性

計算機実験は確率的に行われているので，
乱数系列の違いによって結果は当然ばらつくことになる．
以下の実験では，このばらつきがどの程度あるかを確認する．
不確定性の原因(乱数によって生成している項目)としては
- 集団のネットワーク
- 感染の発生源
- 発症した患者から未感染者への感染
のばらつきが考えられる．

多数回の実験により可能性を網羅したい．
複数回の実験はコストが掛かる
単一の実験で済むなら済ませたい．
単一の実験からわかることとわからないことを見極める必要がある．
知りたいことが単一の実験でわかるなら，
単一の実験でよい．
わからないなら多数回繰り返して確認する必要がある．

ここでも集団のネットワークには
Watts-Strogatzのモデルを用いることとし，
実験の基本的な設定を表\ref{tab:exp2}にまとめる．

#+begin_export latex
\begin{margintable}
  \caption{実験設定}
  \label{tab:exp2}
  % \centering
  \small
  \begin{tabular}{ll}
    \toprule
    パラメタ&値 \\
    \midrule
    頂点数&10000 \\
    初期近傍&50\;($25\times2$) \\
    張替確率&0.05 \\
    感染確率&0.04 \\
    潜伏期間&3 \\
    媒介期間&3 \\
    \bottomrule
  \end{tabular}
\end{margintable}
#+end_export

まず，
集団のネットワークも初期値も固定して，
感染が起こるかどうかのみランダムに選択したとき，
どの程度結果に違いがあるのか確認する．
感染拡大の推移を図\ref{fig:exp2-1}に示す．
左は集団全体に対する感染者の比率の推移を，
右は感染者数の対数値の推移を示したものである．
初期の拡がり方にばらつきはあるものの，
感染が拡大してからの速度はほぼ同じである．[fn:4]
したがって，
感染が起こるかどうかの確率的な選択は
拡大開始の時期に影響を与えるが，
拡大の速度にはほとんど影響しないことがわかる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \GraphFile{figs/exp2}
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{感染者の確率的な選択によるばらつき．
    感染拡大の始まる時期は異なるが，
    拡大の指数的な速度の性質はほとんど変わならいことがわかる．
    \label{fig:exp2-1}}
\end{figure*}
#+end_export

次に初期値の違いによるばらつきを確認する．
集団のネットワークを固定して，
初期値をランダムに変えて実験した結果を
図\ref{fig:exp2-2}に示す．
図\ref{fig:exp2-1}と同様に
感染拡大が開始される時間にばらつきがあるが，
拡大速度はほぼ同様であることが確認できる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{初期値の違いによるばらつき．
    前の場合と同様に，
    感染拡大の始まる時期は異なるが，
    拡大の指数的な速度の性質はほとんど変わならいことがわかる．
    \label{fig:exp2-2}}
\end{figure*}
#+end_export

最後に，
集団のネットワークの違いによる
感染拡大の推移を図\ref{fig:exp2-3}に示す．
前の実験と同様に，
初期の拡がり方にばらつきはあるものの，
感染が拡大してからの速度はほぼ同じである．
したがって，集団のネットワークの特性が同じであれば，
感染拡大の推移は同様であることがわかる．
ただし，
またネットワークの違いによるばらつきは，
他に比べると大きくなる傾向があることがわかる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{集団のネットワークの違いによるばらつき．
    前の実験と同様に，
    感染拡大の動的な性質はほとんど変わならいことがわかる．
    ただし，ネットワークが異なる場合は
    ばらつきが大きい傾向がある．
    \label{fig:exp2-3}}
\end{figure*}
#+end_export

以上より，
確率的なシミュレーションにより，
感染の拡大が始まる時期にばらつきがあるものの，
拡大の動的な性質は維持されていることがわかる．
以下では，
多数回の計算機実験を行わずに，
1つの実験結果を見ながら
ある程度の定性的な議論を行うこととする．

* グラフ構造の特性の影響

集団の関係のモデルである
グラフの構造の違いが，
感染の拡大にどのように影響を与えるか見てみよう．

グラフの生成モデルは様々なものが提案されているが，
ここまで使っていた
Watts-Strogatzのモデルに限定して，
その生成パラメタの変化が感染の拡がり方に及ぼす影響を見てみる．

先にも述べたように
Watts-Strogatzのモデルは
規則的なグラフとランダムグラフの中間的なグラフ構造を
生成することができるが，
ここで議論するパラメタとして
- 初期値として与える規則的なグラフの近傍数(小さければ疎，大きければ密)
- 張り替えの確率(小さければ規則的，大きければランダム)
を考える．

まず，初期グラフの近傍数を変えた場合の影響を調べた結果を
図\ref{fig:exp3-1}に示す．
左右の図はそれぞれ，
前節と同様に感染率と感染者数の対数の推移である．

近傍数が最も小さい10としたときは，
感染は集団全体に拡がることなく局所的が発症のみで終息している．
それ以外では感染はほぼ蔓延しているが，
近傍数が少ない場合には拡大の速度が小さい．
ただし，ある程度の近傍数になると速度にそれほど大きな違いはない．
感染に必要な辺は片方が
一定以上の近傍があれば十分な速度で伝播してしまっていて，
辺の両端が感染者になってしまうから

任意の2頂点間を行き来する平均的な辺の数はあまり変わらない

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \GraphFile{figs/exp3}
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{近傍数の影響．
    \label{fig:exp3-1}}
\end{figure*}
#+end_export

次に，
張替確率を0から1まで変えた場合の影響を調べた結果を
図\ref{fig:exp3-2}に示す．
張替確率が0の場合は近傍数が一定の規則的なグラフ(リング状の)，
1の場合は平均近傍数が初期値グラフと同じランダムグラフ

確率が0の場合は，
感染の伝播が一定数で増加する特殊な伝播

それ以外は一旦拡大しはじめると
指数的に増加して，
最終的には蔓延する

ランダムネスとはあまり関係なく
ほぼ同じ速度で感染が拡大している

規則的な構造の場合のみ特殊
ランダムネスがちょっとあるだけで性質ががらりと変わる．


#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{張替確率の影響．
    \label{fig:exp3-2}}
\end{figure*}
#+end_export

* 感染モデルの特性の影響

単位時間を1日として話をしよう．

潜伏期間が長ければ，
感染の拡大速度が遅くなる

感染率の推移だけ見ると
拡大が始まる時期がずれているように見えるが，
対数表示すると明瞭に
指数増大の傾きが単調に減少していることがわかる．

潜伏期間の長さは速度に影響を与える．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \GraphFile{figs/exp4}
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{潜伏期間の影響．
    \label{fig:exp4-1}}
\end{figure*}
#+end_export

媒介期間が長ければ
接触機会も増え，
実質的な感染の確率が増大する
ことが予想される．
単調に増えるわけではない．

辺での感染確率はほぼ1になる
1への近づき方は非常に速いので
ある程度以上に媒介期間が長ければ影響は変わらない．

単純に計算
0.04*50*3 >1  なので

近傍の誰にも感染しない確率は?
(1-0.04)^50

媒介期間，隔離されるまで隣の人にうつさない確率
(1-0.04)^媒介期間 

うつす確率
1-(1-0.04)^媒介期間

全ての人うつさない確率
(1-0.04)^(媒介期間*次数) <- 非常に小さい

うつす確率
1-(1-0.04)^(媒介期間*次数) ほとんど1

次数が大きい場合は媒介期間の長さにはあまりよらずに
感染速度は飽和する．

逆に接触機会を減らすには
発症をすみやかに検知し，
隔離することが重要

感染者が隔離されるまでに1を越える人に感染させれば，
指数的(鼠算的)に感染者は増大する．
したがってこの確率が1を越えるかどうかがクリティカル
ただし，あとで見るように平均的に
この確率が1を越えるかどうかで
単純に決まる問題ではない．
4近傍で0.5がクリティカルというのは説明ができない．

1日の場合は感染速度は遅いが(傾きは小さい)
それ以外は速度にそれほど差はない．
この実験設定では．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{媒介期間の影響．
    \label{fig:exp4-2}}
\end{figure*}
#+end_export

実質上は潜伏期間と媒介期間の比率が重要
この比が感染の速度を決定していると考えられる．

潜伏期間の長さを単位時間と考えれば
両方のパラメタをいじる必要はない
数値実験上は
実際のパラメタと紐付けたいので，
例えば単位時間を1日として，
潜伏期間，媒介期間をそれぞれ日を単位として考えた方がわかりやすい．

感染確率を変えると
少し異なる状況があらわれる

ある確率を境として
蔓延するかしないかが不連続に変化しているように見える

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染の推移}
  \myGraph{感染者の対数表示}
  \sidecaption{感染確率の影響．
    \label{fig:exp4-3}}
\end{figure*}
#+end_export

より詳細にみる．
0.01を境に
ほとんど蔓延せずに終息するか，
大多数に感染が蔓延して終息するかに分岐していることがわかる．
相転移現象の一つ，
パーコレーションの一種と考えられる．

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph{感染の推移}
  \myGraph{感染確率と感染者数}
  \sidecaption{感染確率の影響による相転移．
    \label{fig:exp4-4}}
\end{figure*}
#+end_export
* 感染拡大の相転移

理論的に扱いやすくするために
規則的なグラフ

2次元の格子状に並んだ頂点の集合を考え，
各頂点がその4近傍と辺で結ばれた規則的なグラフを考える．

感染が蔓延するかどうかにだけ興味があるので，
感染の拡大を制御するパラメタについては
できるだけ簡便なものを考える．
表\ref{tab:exp5}のように設定する．

#+begin_export latex
\begin{margintable}
  \caption{実験設定}
  \label{tab:exp5}
  % \centering
  \small
  \begin{tabular}{ll}
    \toprule
    パラメタ&値 \\
    \midrule
    頂点数&10000 \\
    近傍数&4 \\
    潜伏期間&0 \\
    媒介期間&1 \\
    \bottomrule
  \end{tabular}
\end{margintable}
#+end_export

規則的ではあるが，
先の実験と同様に感染が拡大している
指数的ではなく
感染者は線形に増加している
図\ref{fig:exp5-1}に示す．

#+begin_export latex
\begin{figure}[htbp]
  \sidecaption{キャプション
    \label{fig:exp5-1}}
  \centering
  \GraphFile{figs/exp5}
  \myGraph{$t=1$}
  \setcounter{GraphPage}{15}\myGraph{$t=15$}
  \setcounter{GraphPage}{30}\myGraph{$t=30$}
  \setcounter{GraphPage}{45}\myGraph{$t=45$}
  \setcounter{GraphPage}{60}\myGraph{$t=60$}
  \myGraph{感染の推移}
\end{figure}
#+end_export

感染確率を変えて
複数回実験した結果を
図\ref{fig:exp5-2}に示す．

#+begin_export latex
\begin{figure}[htbp]
  \sidecaption{キャプション
    \label{fig:exp5-2}}
  \centering
  \myGraph*{感染確率と感染率の関係}
\end{figure}
#+end_export

十分時間が経過したあとの終息結果
感染確率の違いにより感染率が変わる．
蔓延の仕方が異なる．
図\ref{fig:exp5-3}に示す．

図\ref{fig:exp5-2}で見たように
局所

#+begin_export latex
\begin{figure*}%[htbp]
  \centering
  \myGraph[.3]{感染確率$=0.2$}
  \myGraph[.3]{感染確率$=0.5$}
  \myGraph[.3]{感染確率$=0.7$}
  \sidecaption{キャプション
    \label{fig:exp5-3}}
\end{figure*}
#+end_export


近似的な解析

無限遠点の極限を考える．
#+begin_export latex
\begin{equation}
  Q
  =\Pr{\text{頂点$i$から無限遠点まで感染しない}}
  \quad\text{(頂点$i$によらない)}
\end{equation}
#+end_export
  
簡単な帰納的
#+begin_export latex
\begin{align}
  Q
  &=\Pr{\text{頂点$i$から無限遠点に到達する経路がない}}\\
  &=\Pr{\text{頂点$i$の4近傍を経由して無限遠点に到達する経路がない}}\\
  &\simeq\Pr{\text{頂点$i$の1つの近傍$j$を経由して無限遠点に到達する経路がない}}^{4}\\
  &=\Pr{\text{頂点$i$から近傍に経路がない}\text{または}
    \text{近傍から経路がない}}^{4}\\
  &=\bigl(
    \underbrace{P_{\phantom{j}}}_{i\to j}
    \cdot\underbrace{Q}_{j\not\to\infty}+
    \underbrace{(1-P)}_{i\not\to j}
    \bigr)^{4}
\end{align}
#+end_export

4近傍の各点から無限遠への経路の有無は独立ではないので，
式は近似である．


感染確率 $P$ に対して
以下の式を満たす $Q$ がどのような値となるかを考えればよい．
#+begin_export latex
\begin{equation}
  Q=\{P\times Q + (1-P)\}^{4},\;0<Q<1
\end{equation}
#+end_export

#+begin_export latex
\begin{figure}%[htbp]
  \sidecaption{確率$Q$の満たす条件．
    \label{fig:exp6-1}}
  \centering
  \GraphFile{figs/exp6}
  \myGraph*{}
\end{figure}
#+end_export

この条件を図示すると
図\ref{fig:exp6-1}のようになる．
図は横軸を $Q$
縦軸を $R$ として
2つの関数
#+begin_export latex
\begin{align}
  R&=Q\\
  R&=\{P\times Q + (1-P)\}^{4}
\end{align}
#+end_export
を重ね描きしたもの
区間 $0\le Q\le 1$ に含まれる交点が，
条件を満たす $Q$ の値となる．
感染確率 $P$ の大小によって
解が $0\le Q\le 1$ の間を移動していく様子がわかる．

#+begin_export latex
\begin{figure}%[htbp]
  \sidecaption{感染確率と全感染率の関係．
    \label{fig:exp6-2}}
  \centering
  \myGraph*{}
\end{figure}
#+end_export

確率 $Q$ は感染が拡がらない確率なので，
終息期の全感染率は $1-Q$ で表される．
感染確率 $P$ と 
全感染率 $1-Q$ の関係を示すと
図\ref{fig:exp6-2}となる．
これから閾値(この場合は $p=0.25$)を越えると
急速に全感染率が1に近付いくていことがわかる．

* おわりに

感染症の場合，
人間が対応して変えられるのは
感染確率のみ

集団のネットワークは変えようがない．

感染確率は
接触機会と感染力の積

感染力はウイルス固有のものなので，
接触機会を減らすしかない．

感染確率を減らすことによって
蔓延を避けることができる．
ある閾値以下であれば，
局所的な感染で済むかもしれない．
蔓延するにしても拡大の速度を減少させ，
治療のための時間を稼ぐことができるかもしれない．

治療方法の確立，
治療体制の確保，
治療薬・予防薬，ワクチンの開発

状態としては二つ

孤立した領域での発症で済むか
全体に蔓延して終息

指数的に拡大していく場合には
指数の増大を決める時定数を小さくすることが必要

モデルの中のパラメタとこの時定数の関係を見てきた

結局人間がいじれるのは限られている．


* Footnotes

[fn:4]感染の拡大期には患者数は指数的に増加するが，
指数の係数は感染者数の対数を示した右図の傾きからわかる．

[fn:3]医学的な用語とは齟齬があるが，
モデルを簡潔に記述するために
発症してはじめて他者に感染させる可能性がある
ものとして扱う．

[fn:2]接触機会に対して必ずしも感染が起こるとは限らないので，
この不確定性を確率的なものとして取り扱う．
接触機会として濃厚接触のみを考える場合は，
感染確率を1に近づければよい．

[fn:1]ここで考える接触はいわゆる濃厚接触に限らず，
比較的密集した空間に同時に留まることがあり，
感染を引き起こす可能性のあるものを含めて考えることとする．
例えば，
会社の同じ部署にいる，
あるいは同じエレベータや電車などを使うなどを想定すれば良い．
 
